In [ ]:
pip install GEOMINE

In [ ]:
import numpy as np
import GEOMINE  # not graphletorbit!

# Example graph from the docs
Example = np.matrix([
    [0,1,1,0,0,0],
    [1,0,1,0,0,0],
    [1,1,0,1,1,0],
    [0,0,1,0,0,0],
    [0,0,1,0,0,1],
    [0,0,0,0,1,0]
])




 Count orbits of order 4 with 1 vertex color and 1 edge colors
 Count(G, ref, k, sizev, sizee, connect = False}) ,
- G is the adjacency matrix of the graph,
- ref is
- k is the max number of verticies of the graphlets,
- sizev is the number of type of verticies
- **sizee is the number of types of edges +1**


In [ ]:

result = GEOMINE.Count(Example, 1, 4, 1, 2, True)
print(result)

[1 0 1 2 0 0 0 0 0 0 0]


In [ ]:
# Generate graphlets
graphlets = GEOMINE.Generator(3, sizev=1, sizee=2, orbg=False, connect=True)

print("number of graphlets", len(graphlets))

# Take first graphlet serialization
L = graphlets[0]

# Convert back to adjacency matrix
A = GEOMINE.lis2mat(L, 3)
print(A)

number of graphlets 2
[[0 0 1]
 [0 0 1]
 [1 1 0]]


In [ ]:
#Now we set orbg to true. In this way we generate for each graphlets all its orbits . The output leght will match the output of count

In [ ]:
# Generate graphlets
graphletsOrb = GEOMINE.Generator(3, sizev=1, sizee=2, orbg=True, connect=True)

print("number of orbits", len(graphletsOrb))

number of orbits 3


In [ ]:
# Take first graphlet serialization
L = graphletsOrb[1]

# Convert back to adjacency matrix
A = GEOMINE.lis2mat(L, 3)
print(A)

[[0 1 1]
 [1 0 0]
 [1 0 0]]
