# Loading graph data

In [19]:
#!pip install pandas
#!pip install scipy
#!pip install networkx 
#!pip install scikit-learn
#!pip install sympy

In [ ]:
import pandas as pd # DataFrame library
from scipy.sparse import csr_matrix # sparse matrix library
import networkx as nx # graph library
import ast # no need to install
import numpy as np 
from fractions import Fraction # rational numbers type
import sympy as sp # computation with rational numbers

First let's access the directory consolidated_data where the graph data are stored

In [5]:
import os
folder_path = "../consolidated_data"
print(os.listdir(folder_path))

['fGraph_edges_3.tex', 'fGraph_dials_4.tex', 'amplitudeCoefficients_7.tex', 'fGraph_edges_4.tex', 'amplitudeCoefficients_6.tex', 'fGraph_dials_6.tex', 'fGraph_nums_5.tex', 'fGraph_dials_9.tex', 'fGraph_edges_2.tex', 'amplitudeCoefficients_1.tex', 'fGraph_nums_6.tex', 'fGraph_dials_1.tex', 'amplitudeCoefficients_3.tex', 'fGraph_nums_10.tex', 'amplitudeCoefficients_2.tex', 'fGraph_nums_2.tex', 'fGraph_edges_8.tex', 'fGraph_edges_5.tex', 'fGraph_edges_1.tex', 'fGraph_edges_6.tex', 'fGraph_dials_10.tex', 'amplitudeCoefficients_8.tex', 'fGraph_edges_9.tex', 'amplitudeCoefficients_5.tex', 'consolidated_correlator_data.nb', 'fGraph_nums_3.tex', 'fGraph_nums_8.tex', 'fGraph_dials_2.tex', 'amplitudeCoefficients_4.tex', 'fGraph_dials_8.tex', 'fGraph_dials_3.tex', 'fGraph_nums_9.tex', 'fGraph_edges_7.tex', 'amplitudeCoefficients_9.tex', 'fGraph_nums_7.tex', 'fGraph_dials_5.tex', 'fGraph_nums_4.tex', 'fGraph_nums_1.tex', 'fGraph_dials_7.tex', 'fGraph_edges_10.tex', 'amplitudeCoefficients_10.tex']


Load amplitudes coefficients for a fixed number of loops

In [6]:
loop = "7"

## Import graph data

In [7]:
# Load the file "graph_edges_loop.csv" containg the graph data
path_file = 'graph_data_'+loop+'.csv'
# Read the CSV file into a DataFrame
df = pd.read_csv(path_file)
# convert sting elements to expressions
df["DEN_EDGES"] = df["DEN_EDGES"].apply(ast.literal_eval)
df["NUM_EDGES"] = df["NUM_EDGES"].apply(ast.literal_eval)


In [8]:
#Check number of zero coeffcients
sum(df.COEFFICIENTS ==0), sum(df.COEFFICIENTS !=0)

(93, 127)

## Normalize rational coefficients to integers

In [10]:
# Multiply by the biggest denominator
#max_denominator = max(num.denominator for num in coefs)
# Convert to integers
#coefs = [num.numerator * (max_denominator // num.denominator) for num in coefs]
#len(coefs)

# Graph example

In [13]:
import networkx as nx

# Define your lists of edges
den_edges = df.iloc[10,1]
num_edges = df.iloc[10,2]

# Create a MultiGraph
G = nx.MultiGraph()

# Add friendship edges with the edge_type attribute
for u, v in den_edges:
    G.add_edge(u, v, edge_type="den")

# Add colleague edges with the edge_type attribute
for u, v in num_edges:
    G.add_edge(u, v, edge_type="num")

# Inspect the edges, note each edge has an extra key identifier to deal with double edges
for u, v, key, data in G.edges(keys=True, data=True):
    print(f"Edge from {u} to {v} (key: {key}) has type: {data['edge_type']}")


Edge from 1 to 5 (key: 0) has type: den
Edge from 1 to 7 (key: 0) has type: den
Edge from 1 to 8 (key: 0) has type: den
Edge from 1 to 11 (key: 0) has type: den
Edge from 5 to 2 (key: 0) has type: den
Edge from 5 to 6 (key: 0) has type: den
Edge from 5 to 7 (key: 0) has type: den
Edge from 5 to 11 (key: 0) has type: den
Edge from 5 to 8 (key: 0) has type: num
Edge from 7 to 6 (key: 0) has type: den
Edge from 7 to 8 (key: 0) has type: den
Edge from 7 to 10 (key: 0) has type: den
Edge from 7 to 9 (key: 0) has type: num
Edge from 8 to 4 (key: 0) has type: den
Edge from 8 to 10 (key: 0) has type: den
Edge from 8 to 11 (key: 0) has type: den
Edge from 11 to 2 (key: 0) has type: den
Edge from 11 to 3 (key: 0) has type: den
Edge from 11 to 4 (key: 0) has type: den
Edge from 11 to 9 (key: 0) has type: den
Edge from 11 to 6 (key: 0) has type: num
Edge from 11 to 10 (key: 0) has type: num
Edge from 11 to 10 (key: 1) has type: num
Edge from 2 to 6 (key: 0) has type: den
Edge from 2 to 9 (key: 0) 

In [14]:
# Compute the adjacency matrix.
# Note: For MultiGraphs, the matrix entries sum the weights of parallel edges.
A = nx.to_numpy_array(G)

print("Adjacency Matrix:")
print(A)

Adjacency Matrix:
[[0. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 1. 1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 0. 1. 0. 0. 1. 1. 0. 0. 1.]
 [1. 1. 1. 0. 1. 0. 0. 0. 0. 1. 1.]
 [1. 1. 0. 1. 0. 1. 1. 1. 1. 1. 2.]
 [0. 1. 0. 0. 1. 0. 1. 1. 0. 0. 0.]
 [0. 1. 1. 0. 1. 1. 0. 1. 0. 0. 1.]
 [0. 0. 1. 0. 1. 1. 1. 0. 1. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0. 1. 0. 1. 1.]
 [0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 1.]
 [0. 0. 1. 1. 2. 0. 1. 1. 1. 1. 0.]]


In [15]:

# Compute the eigenvalues of the adjacency matrix
eigenvalues = np.linalg.eigvals(A)

print("Eigenvalues:")
print(eigenvalues)


Eigenvalues:
[ 6.2827296  -2.88654654  2.11748141  1.72239291 -2.1557411  -1.4550446
 -0.81277653 -0.29498512  0.48248998 -2.         -1.        ]
