# Loading graph data

In [115]:
#!pip install pandas
#!pip install scipy
#!pip install networkx 
#!pip install scikit-learn
#!pip install sympy

In [119]:
import pandas as pd # DataFrame library
from scipy.sparse import csr_matrix # sparse matrix library
import networkx as nx # graph library
import ast # no need to install
import numpy as np 
from fractions import Fraction # rational numbers type
import sympy as sp # computation with rational numbers
import pickle # serialization library

First let's access the directory consolidated_data where the graph data are stored

In [120]:
import os
folder_path = "../consolidated_data"
print(os.listdir(folder_path))

['fGraph_edges_3.tex', 'fGraph_dials_4.tex', 'amplitudeCoefficients_7.tex', 'fGraph_edges_4.tex', 'amplitudeCoefficients_6.tex', 'fGraph_dials_6.tex', 'fGraph_nums_5.tex', 'fGraph_dials_9.tex', 'fGraph_edges_2.tex', 'amplitudeCoefficients_1.tex', 'fGraph_nums_6.tex', 'fGraph_dials_1.tex', 'amplitudeCoefficients_3.tex', 'fGraph_nums_10.tex', 'amplitudeCoefficients_2.tex', 'fGraph_nums_2.tex', 'fGraph_edges_8.tex', 'fGraph_edges_5.tex', 'fGraph_edges_1.tex', 'fGraph_edges_6.tex', 'fGraph_dials_10.tex', 'amplitudeCoefficients_8.tex', 'fGraph_edges_9.tex', 'amplitudeCoefficients_5.tex', 'consolidated_correlator_data.nb', 'fGraph_nums_3.tex', 'fGraph_nums_8.tex', 'fGraph_dials_2.tex', 'amplitudeCoefficients_4.tex', 'fGraph_dials_8.tex', 'fGraph_dials_3.tex', 'fGraph_nums_9.tex', 'fGraph_edges_7.tex', 'amplitudeCoefficients_9.tex', 'fGraph_nums_7.tex', 'fGraph_dials_5.tex', 'fGraph_nums_4.tex', 'fGraph_nums_1.tex', 'fGraph_dials_7.tex', 'fGraph_edges_10.tex', 'amplitudeCoefficients_10.tex']


Load amplitudes coefficients for a fixed number of loops

In [121]:
loop = "7"

## Import graph data

In [122]:
# Load the file "graph_edges_loop.csv" containg the graph data
path_file = 'graph_data_'+loop+'.csv'
# Read the CSV file into a DataFrame
df = pd.read_csv(path_file)
# convert sting elements to expressions
df["DEN_EDGES"] = df["DEN_EDGES"].apply(ast.literal_eval)
df["NUM_EDGES"] = df["NUM_EDGES"].apply(ast.literal_eval)


In [123]:
#Check number of zero coeffcients
sum(df.COEFFICIENTS ==0), sum(df.COEFFICIENTS !=0)

(93, 127)

## Normalize rational coefficients to integers

In [10]:
# Multiply by the biggest denominator
#max_denominator = max(num.denominator for num in coefs)
# Convert to integers
#coefs = [num.numerator * (max_denominator // num.denominator) for num in coefs]
#len(coefs)

# Graph

## Example graph definition and manipulation

In [ ]:
# Define your lists of edges
den_edges = df.iloc[10,1]
num_edges = df.iloc[10,2]

# Create a MultiGraph
G = nx.MultiGraph()

# Add friendship edges with the edge_type attribute
for u, v in den_edges:
    G.add_edge(u, v, edge_type="den")

# Add colleague edges with the edge_type attribute
for u, v in num_edges:
    G.add_edge(u, v, edge_type="num")

# Inspect the edges, note each edge has an extra key identifier to deal with double edges
for u, v, key, data in G.edges(keys=True, data=True):
    print(f"Edge from {u} to {v} (key: {key}) has type: {data['edge_type']}")


Edge from 1 to 5 (key: 0) has type: den
Edge from 1 to 7 (key: 0) has type: den
Edge from 1 to 8 (key: 0) has type: den
Edge from 1 to 11 (key: 0) has type: den
Edge from 5 to 2 (key: 0) has type: den
Edge from 5 to 6 (key: 0) has type: den
Edge from 5 to 7 (key: 0) has type: den
Edge from 5 to 11 (key: 0) has type: den
Edge from 5 to 8 (key: 0) has type: num
Edge from 7 to 6 (key: 0) has type: den
Edge from 7 to 8 (key: 0) has type: den
Edge from 7 to 10 (key: 0) has type: den
Edge from 7 to 9 (key: 0) has type: num
Edge from 8 to 4 (key: 0) has type: den
Edge from 8 to 10 (key: 0) has type: den
Edge from 8 to 11 (key: 0) has type: den
Edge from 11 to 2 (key: 0) has type: den
Edge from 11 to 3 (key: 0) has type: den
Edge from 11 to 4 (key: 0) has type: den
Edge from 11 to 9 (key: 0) has type: den
Edge from 11 to 6 (key: 0) has type: num
Edge from 11 to 10 (key: 0) has type: num
Edge from 11 to 10 (key: 1) has type: num
Edge from 2 to 6 (key: 0) has type: den
Edge from 2 to 9 (key: 0) 

In [29]:
# Compute the adjacency matrix.
# Note: For MultiGraphs, the matrix entries sum the weights of parallel edges.
A = nx.to_numpy_array(G)

print("Adjacency Matrix:")
print(A)

# Compute the eigenvalues of the adjacency matrix as floats
eigenvalues = np.linalg.eigvals(A)
eigenvalues.sort() # sort the eigenvales

print("Eigenvalues:")
print(eigenvalues)

Adjacency Matrix:
[[0. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 1. 1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 0. 1. 0. 0. 1. 1. 0. 0. 1.]
 [1. 1. 1. 0. 1. 0. 0. 0. 0. 1. 1.]
 [1. 1. 0. 1. 0. 1. 1. 1. 1. 1. 2.]
 [0. 1. 0. 0. 1. 0. 1. 1. 0. 0. 0.]
 [0. 1. 1. 0. 1. 1. 0. 1. 0. 0. 1.]
 [0. 0. 1. 0. 1. 1. 1. 0. 1. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0. 1. 0. 1. 1.]
 [0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 1.]
 [0. 0. 1. 1. 2. 0. 1. 1. 1. 1. 0.]]
Eigenvalues:
[-2.88654654 -2.1557411  -2.         -1.4550446  -1.         -0.81277653
 -0.29498512  0.48248998  1.72239291  2.11748141  6.2827296 ]


## Adjacency matrix eigenvalues

In [118]:
# eval(edges) computes the adjacency matrix eigenvalues from a list of edges
def eVal(edges):
    #define graph
    G = nx.MultiGraph(edges)
    # Compute adjacenct matrix
    A = nx.to_numpy_array(G)
    # Compute the eigenvalues
    eigenvaluesG = np.linalg.eigvalsh(A)
    # Sort the eigenvalues
    eigenvaluesG.sort()
    return eigenvaluesG

In [124]:
#taking care of empty numerators
df["NUM_EDGES"] = df["NUM_EDGES"].apply(lambda x: [] if x == () else x)

In [125]:
df["EV_DEN"] =df["DEN_EDGES"].apply(eVal)

In [134]:
df["EV_FGRAPH"] = (df["NUM_EDGES"]+df["DEN_EDGES"]).apply(eVal)

In [131]:
example =(df["NUM_EDGES"]+df["DEN_EDGES"]).iloc[1]

In [133]:
eVal(example)

array([-2.99030288, -2.50608944, -1.76588923, -1.16262908, -1.        ,
       -0.71508912, -0.25700541,  1.06555372,  1.28390787,  2.07892909,
        5.96861448])

In [135]:
#dataframe without edges
df_eigen = df.drop(columns=["DEN_EDGES", "NUM_EDGES"])

let make a column for each eigenvalue

In [136]:
def columsName(name,n):
    return [name + str(i) for i in range(n)]

In [137]:
# Create a new DataFrame from the lists with custom column names
new_cols_den = pd.DataFrame(df_eigen['EV_DEN'].apply(lambda x: x.tolist()).tolist(), columns =columsName('EV_DEN', len(df_eigen['EV_DEN'][0])))
# Create a new DataFrame from the lists with custom column names
new_cols_fgraph = pd.DataFrame(df_eigen['EV_FGRAPH'].apply(lambda x: x.tolist()).tolist(), columns =columsName('EV_FGRAPH', len(df_eigen['EV_FGRAPH'][0])))

In [138]:
zeroCf= df_eigen["COEFFICIENTS"] == 0
# join the three dataframes
df_eigen = pd.concat([zeroCf, new_cols_den, new_cols_fgraph], axis=1)

In [116]:
# keep only 4 digits
df_eigen.map(lambda x: round(x, 4) if isinstance(x, float) else x)

COEFFICIENTS  EV_DEN0  EV_DEN1  EV_DEN2  EV_DEN3  EV_DEN4  EV_DEN5  \
0           False  -2.2361  -2.2258  -1.7321  -1.7321   -1.000  -1.0000   
1            True  -2.2361  -2.2258  -1.7321  -1.7321   -1.000  -1.0000   
2           False  -2.2361  -2.2258  -1.7321  -1.7321   -1.000  -1.0000   
3           False  -2.2361  -2.2258  -1.7321  -1.7321   -1.000  -1.0000   
4           False  -2.2361  -2.2258  -1.7321  -1.7321   -1.000  -1.0000   
..            ...      ...      ...      ...      ...      ...      ...   
215          True  -2.5369  -2.1966  -1.7554  -1.6573   -1.000  -0.4816   
216          True  -2.9070  -2.0000  -1.7524  -1.5616   -1.000  -0.3074   
217          True  -2.4641  -2.2709  -2.0000  -1.4652   -1.000  -0.1802   
218          True  -2.8807  -2.0000  -1.7457  -1.5456   -0.647  -0.4240   
219          True  -2.4920  -2.0000  -2.0000  -1.3579   -0.618  -0.3729   

     EV_DEN6  EV_DEN7  EV_DEN8  ...          EV_FGRAPH1          EV_FGRAPH2  \
0    -0.7259   1.7321   1.7321  ... -2.303894+0.000000j -1.840576+0.000000j   
1    -0.7259   1.7321   1.7321  ... -2.506089+0.000000j -1.765889+0.000000j   
2    -0.7259   1.7321   1.7321  ... -2.246980+0.000000j -1.788187+0.000000j   
3    -0.7259   1.7321   1.7321  ... -2.739276+0.000000j -1.369836+0.000000j   
4    -0.7259   1.7321   1.7321  ... -2.000000+0.000000j -2.000000+0.000000j   
..       ...      ...      ...  ...                 ...                 ...   
215  -0.2213   1.1938   1.5071  ... -2.077102+0.000000j -1.503819+0.000000j   
216  -0.0000   1.0000   1.0362  ... -2.000000+0.000000j -1.850075+0.000000j   
217   0.0000   1.0000   1.2527  ... -2.000000+0.000000j -1.661600+0.000000j   
218   0.0000   0.3520   1.4172  ... -2.000000-0.000000j -2.000000+0.000000j   
219  -0.0000  -0.0000   1.6180  ... -2.186100+0.000000j -2.000000+0.000000j   

             EV_FGRAPH3          EV_FGRAPH4  \
0   -1.620863+0.000000j -0.927202+0.000000j   
1   -1.162629+0.000000j -1.000000+0.000000j   
2   -1.339591+0.000000j -1.000000+0.000000j   
3   -1.000000+0.000000j -1.000000+0.000000j   
4   -2.000000+0.000000j -1.302776+0.000000j   
..                  ...                 ...   
215 -1.000000+0.000000j -1.000000+0.000000j   
216 -1.196383+0.000000j -1.000000+0.000000j   
217 -1.498124+0.000000j -1.000000+0.000000j   
218 -2.000000+0.000000j -0.732051+0.000000j   
219 -1.342436+0.000000j -0.688892+0.000000j   

                                         EV_FGRAPH5  \
0   -7.108120e-01+0.000000e+                    00j   
1   -7.150891e-01+0.000000e+                    00j   
2   -7.035040e-01+0.000000e+                    00j   
3   -1.000000e+00+0.000000e+                    00j   
4   -7.448589e-01+0.000000e+                    00j   
..                                              ...   
215 -7.758250e-01+0.000000e+                    00j   
216 -4.142136e-01+0.000000e+                    00j   
217 -3.312993e-01+0.000000e+                    00j   
218 -4.996004e-16+0.000000e+                    00j   
219 -5.320540e-17-4.007114e-                    17j   

                                         EV_FGRAPH6  \
0   -6.179374e-01+0.000000e+                    00j   
1   -2.570054e-01+0.000000e+                    00j   
2   -5.549581e-01+0.000000e+                    00j   
3   -2.555734e-01+0.000000e+                    00j   
4    2.463693e-16+0.000000e+                    00j   
..                                              ...   
215 -7.754735e-17+0.000000e+                    00j   
216 -2.679492e-01+0.000000e+                    00j   
217  4.630772e-01+0.000000e+                    00j   
218 -2.403059e-16+0.000000e+                    00j   
219 -5.320540e-17+4.007114e-                    17j   

                                         EV_FGRAPH7          EV_FGRAPH8  \
0    1.078995e+00+0.000000e+                    00j  1.291095+0.000000j   
1    1.065554e+00+0.000000e+                    00j  1.283908+0.000000j   
2    8.019377e-01+0.000000e+               

In [117]:
# save the dataframe to a pickle file
df_eigen.to_pickle("eigenvalues_graph"+loop+".pkl")